### ISSUE TITLE
CircileCI tweaks

### ISSUE THREAD

**Issue by patch0** [RaspberryPiFoundation/rpi-auth#2]
Sorry, this is a bit of a post-hoc review, but here goes.

```yaml
version: 2.1
orbs:
  ruby: circleci/ruby@1.1.4

jobs:
  build:
    docker:
      - image: cimg/ruby:2.7.2-node
    steps:
      - checkout
      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/install-deps

  test:
    docker:
      - image: cimg/ruby:2.7.2-node
    steps:
      - checkout
      - ruby/install-deps
      - ruby/rspec-test

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
```

* The build task doesn't do anything that's not in the test task.
* Ruby 2.7.2 is two releases behind.  I guess it might be easier just to specify 2.7, without the minor version.
* I don't think you need `-node`? 
* Is it worth testing against ruby 2.7 and ruby 3? 
* A rubocop task would be good for linting.  I made a set of [rubocop configs](https://raspberrypifoundation.github.io/digital-engineering/configs/) a few months ago.
* It'd be great to have a `publish` task too, so publishing is automated. Not sure how easy that would be though.

The [Code Club](https://github.com/RaspberryPiFoundation/codeclub/blob/main/.circleci/config.yml) and [Projects](https://github.com/RaspberryPiFoundation/projects-admin/blob/main/.circleci/config.yml) configs are recent examples.

Sorry, this is a bit of a raft of minor changes.
